### ISSUE TITLE
Feature request: Ontap volume autogrow setting

### ISSUE THREAD

**Issue by lopf** [NetApp/trident#138]
We usually provision volumes with autogrow enabled. It would be nice if one could specify this via PVC annotations:

`trident.netapp.io/autogrow: true|false`
`trident.netapp.io/autogrowIncrement: <size_in_mb>`
`trident.netapp.io/autogrowMax: <size_in_mb>`

**Comment by wu105** [comment]
@korenaren I have a question on Ontap volume autogrow and feel it is better to add to this issue instead of creating a new:

We are uisng driver ontap-nas and observed that volumes automatically grow when usage approaches 100%.    Is there a place we can look up the following: what is the ontap-nas criteria to trigger the automatic volume size increase?  When the size of a volume is creased automatically, how much does ontap-nas add to the size?

Our backend config is similar to the following:
```
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "ontap-nas_lif_trident_data",
    "managementLIF": "1.2.3.4",
    "dataLIF": "5.6.7.8",
    "svm": "trident_nfs_svm",
    "username": "username",
    "password": "password",
    "defaults": {
      "exportPolicy": "trident_servers",
      "snapshotPolicy": "14_Days"
    }
}
```

By the way, I second the new feature request from @lopf.  The resize capability is for manual volume size management while the request is about automatic volume size increase, quite different operationally.

**Comment by lopf** [comment]
The resizing functionality is not the same as the autogrow. We can resize volumes but if we provision volumes through Trident, we want autogrow to be enabled. Please re-open.

**Comment by adkerr** [comment]
@lopf you are correct that auto grow is different from resize. I think this may have been closed in error. I’ve reopened the issue. 

@wu105: the behavior you see is the ontap auto grow functionality. The trident driver is not controlling this and the setting to adjust what you want are in ontap itself

**Comment by innergy** [comment]
Actually this was closed intentionally. Autogrow would make it impossible to enforce resource limits in k8s and Trident. While the resize feature is not exactly the same, it does allow an end user to ask for more space (which can be automated), which is already a huge improvement over most environments where you need to file a ticket for help, and to do so in a manner that applies any limits in place.

**Comment by wu105** [comment]
@innergy @adkerr What happened in our environment is that there are volume near full alerts not visible to me, and our netapp support reconfigured the volumes with autogrow plus limits without telling me -- thus I initially thought that was an automatic feature of netapp :-)  

The point is that there are manual works on the managing the volumes that might be automated if we can configure the autogrow on the storage class or persistant volume claim.  We can add an autogrow limit as our netapp support did to control the size.  

By the way, when I create a volume of certain size, is that space reserved exclusively for the volume at the very beginning?   If the volume only takes the actual spaces it needs, we can just request for the anticipated max size without needing the auto grow and not wasting the disk space not needed immediately.

**Comment by adkerr** [comment]
@wu105 By default, trident creates ontap volumes as thin provisioned (spaceReserve = none) meaning it will only consume as much disk space as is actually being used. You can override this to be thick (spaceReserve = volume) so that all of the disk space is consumed from the very beginning.

https://netapp-trident.readthedocs.io/en/stable-v19.01/kubernetes/operations/tasks/backends/ontap.html#example-configuration

**Comment by wu105** [comment]
@adkerr Thanks for the clarification on 'thin'!  In a sense 'thin' is all we needed - auto grow with limit without any management overhead.  If we need more control, we can always go to netapp to configure true autogrow, which should be rather rare.
