### ISSUE TITLE
Clarify Docker EE version information in Docker Volume Driver requirements

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#150]
* Docker (CE and EE) 17.03, 17.06, 17.09, and 17.12

https://netapp-trident.readthedocs.io/en/stable-v18.04/support/requirements.html#requirements

Which EE versions are supported?

**Comment by innergy** [comment]
Yes, it's confusing. And the way that Docker names and versions things doesn't help.

Docker has two things named "EE", "Enterprise Engine" (just the engine) and "Enterprise Edition" (the engine, UCP, DTR, etc.). We were originally referring to both, because they shared version numbers in 17.06. But just to keep things interesting, Docker called the latest "Enterprise Edition" version 2.0, it still requires Enterprise Engine 17.06, and will never work with the new Enterprise Engine 18.03:
- https://success.docker.com/article/compatibility-matrix

Clear as day, right?

In summary, we support Docker Enterprise Engine 17.06, Docker Enterprise Edition 17.06, and, with the latest Trident 18.07 beta, Docker Enterprise Edition 2.0, which runs Docker Enterprise Engine 17.06.

Docker Enterprise Engine 18.03 just came out, so we have not qualified it yet, but we don't anticipate any issues. There was a breaking change in the first release of Community Engine 18.03 (18.03.0) that was fixed in 18.03.1, but that issue was fixed before the first 18.03 Enterprise Engine release.

We'll try our best to clarify this in the documentation. Thanks for the report.

**Comment by innergy** [comment]
Fixed by 51c3f4a
