### ISSUE TITLE
Trident SUSE Caas support

### ISSUE THREAD

**Issue by mgranata** [NetApp/trident#179]
Hello, while Trident support Kubertenes and Openshift, I don't see any explicit support for SUSE Caasp nor SUSE Linux host OS. Is there any plan to include these in support?

**Comment by innergy** [comment]
We can't explicitly test with every Kubernetes distribution out there. We have no reason to believe Trident wouldn't work with SUSE CaaS. In fact, we have yet to find a distribution of Kubernetes it didn't work with. If it turned out that there was enough demand for it, and it was different enough from Kubernetes that additional testing was warranted (like OpenShift), we'd do it.

Trident itself is containerized, so it will run on anything with a Linux kernel. The list of host OSes in Trident's documentation is just meant to give you a sense of what we have in Trident's test environment. The real host OS compatibility list is storage platform and protocol specific and comes from NetApp's IMT.

At the end of the day we (NetApp) support Trident, not the Kubernetes distribution (unless it's NKS, of course) or the host OS. If there's a Trident issue, we'll fix it. In the unlikely event that there's an incompatibility with a particular distribution because of some customization that they've done, we'll work with you to figure out where the responsibility lies.
