### ISSUE TITLE
Issue with Trident provisioning RWX (multi user) with Openshift.

### ISSUE THREAD

**Issue by dondsmithtx** [NetApp/trident#182]
We are currently running Trident version 18.07.1.  We are able to provision nfs storage and block storage with single user mode (RWO).  We are unable to provision block storage with multi user (RWX)

Working block storage (RWO):

Oct 12 08:51:12 server1290 journal: time="2018-10-12T13:51:12Z" level=info msg="Kubernetes frontend provisioned a volume and a PV for the PVC." PV=dataes-testing-block-single-user-e0c31 PVC=testing-block-single-user PV_volume=dataes-testing-block-single-user-e0c31

Broken block storage (RWX)

Oct 12 08:51:56 server1290 journal: time="2018-10-12T13:51:56Z" level=warning msg="Kubernetes frontend couldn't provision a volume: no available backends for storage class ontap-value-block (will retry upon resync)" volume=dataes-testing-block-multi-user-fb618

The only error we receive from Trident is "no available backends for storage class ontap-value-block".  Obviously this isn't true since single works which also rules out multipathing.  It is my belief we have a Trident bug.

**Comment by clintonk** [comment]
Hi, @dondsmithtx.  RWX means "read-write-many", where multiple hosts can read and write a volume.  That's not supportable with iSCSI, since the host owns the file system and having multiple writers could lead to data corruption.  If you need multiple hosts to read (& not write) an iSCSI volume, then ROX ("read-only-many") should work.  If you truly need RWX, please use NFS.

**Comment by dondsmithtx** [comment]
Ok that makes perfect sense.  Thanks for the rapid response, I'll close this ticket.
