### ISSUE TITLE
Change of QoS (SolidFire) after provisioning?

### ISSUE THREAD

**Issue by mschindl** [NetApp/trident#187]
Hello,
Is it planned to enhance Trident to change QoS settings (SolidFire) after provisioning?

Brgds, Marc

**Comment by kangarlou** [comment]
QoS settings defined in the SolidFire backend config and Kubernetes storage classes are considered only at the time of provisioning volumes as this is the expected behavior for Kubernetes storage class parameters. Having said that, you can [update the backend definition](https://netapp-trident.readthedocs.io/en/stable-v18.10/kubernetes/operations/tasks/backends.html#updating-a-backend), and if required, recreate the storage class with the new QoS configuration (the parameters section in the Kubernetes storage class is immutable, so you have to delete the storage class and create a new one with the same name) so that new volumes use the desired QoS configuration.
