### ISSUE TITLE
Resizing of NFS share.

### ISSUE THREAD

**Issue by simonpie** [NetApp/trident#21]
Hello,

Trident does not resize a volume on the NetApp filer when the pvc is changed in kubernetes.  In an ideal world, I would love for trident to catch the pvc change and push it to the filer if possible.

I am using trident to create shares on a dedicated NFS SVM.

**Comment by adkerr** [comment]
Internally tracked by [US2426](https://rally1.rallydev.com/#/47479883219d/detail/userstory/111899943100)

**Comment by kangarlou** [comment]
There is currently no mechanism in Kubernetes to update PVs or storage classes and they should be treated as immutable objects. The need for resizing a PV/volume is well known and there is a proposal ([Dynamic changes to PVs](https://docs.google.com/document/d/1EjK6wKuOvPTAF25rzadYVGKLMJm_jFlRXHPOeA3JfUc/edit#heading=h.syy7ailv82pm) that looks into the more general problem of updating PVs. While it's possible to extend Trident to support resizing PVs/volumes before Kubernetes supports such capability via updates to PVCs, any such effort should take into account _possible_ implications on other components and activities (e.g., storage quota management by Kubernetes).

**Comment by dutchiechris** [comment]
Just a note that resizing of PVs if capacity of PVC is increased is targeted for k8s 1.8; see https://github.com/kubernetes/features/issues/284 and [Grow design proposal](https://github.com/gnufied/community/blob/91b41028182a5291b4eccbf88f8065f66b2b7eed/contributors/design-proposals/grow-volume-size.md)

In the design proposal it says NFS and iSCSI would not support resize though.  I'm not sure if this is relevant if Trident manages (out of tree), or if maybe if k8s will reject an edit because it *thinks* the underlying NFS/iSCSI PV type doesn't support it.  Could be something to check with those contributing the feature...

**Comment by acsulli** [comment]
+1 for this from a(nother) customer.  

Also, the Kubernetes feature request @dutchiechris referenced has been updated to reflect target timelines (1.11 beta, 1.12 GA).

**Comment by wavezhang** [comment]
+1,  we need this feature too

**Comment by tothebit9** [comment]
+1 we are looking forward to this feature. : )

**Comment by joceluss** [comment]
+1

**Comment by ivnilv** [comment]
+1

**Comment by hartman17** [comment]
+1

**Comment by kangarlou** [comment]
For volume resize to work with Trident, we need to patch k8s upstream to allow resizing NFS and iSCSI PVs. I'm working on this patch, but this means you should expect volume resize with k8s 1.12 at the earliest.

**Comment by winggundamth** [comment]
@kangarlou Can you post pull request on upstream so we can track the progress :)

**Comment by kangarlou** [comment]
@winggundamth You can follow the PR here: https://github.com/kubernetes/kubernetes/pull/66780

**Comment by canhnt** [comment]
+1 We are waiting for this feature
