### ISSUE TITLE
RFE: Allow volume configurations to be set in StorageClass as parameter or annotation

### ISSUE THREAD

**Issue by djboris9** [NetApp/trident#22]
Hi there

As a Kubernetes administrator I would like to blueprint newly created volumes to specify configuration defaults or to comply with company standards.

In order to achive this user story I propose to extend the Kubernetes StorageClass for Trident by the same annotations as PersistentVolumeClaims or in volume.json (Trident Volume Configuration):

- trident.netapp.io/protocol
- trident.netapp.io/exportPolicy
- trident.netapp.io/snapshotPolicy
- trident.netapp.io/snapshotDirectory
- trident.netapp.io/unixPermissions
- trident.netapp.io/reclaimPolicy

This would allow to define StorageClass'es like this:

	apiVersion: storage.k8s.io/v1beta1
	kind: StorageClass
	metadata:
	  annotations:
	    trident.netapp.io/exportPolicy: trident_openshift
	    trident.netapp.io/reclaimPolicy: Retain
	  creationTimestamp: null
	  name: basic
	parameters:
	  backendType: ontap-nas
	  requiredStorage: ontapnas_10.10.10.10:aggr_nas01_data
	provisioner: netapp.io/trident

An alternative solution would be to pass these configurations in the parameters section:

	apiVersion: storage.k8s.io/v1beta1
	kind: StorageClass
	metadata:
	  creationTimestamp: null
	  name: basic
	parameters:
	  backendType: ontap-nas
	  requiredStorage: ontapnas_10.10.10.10:aggr_nas01_data
	  exportPolicy: trident_openshift
	  reclaimPolicy: Retain
	provisioner: netapp.io/trident

The downside of the latter aproach is, that the StorageClass must be recreated in order to change these configurations.

In case of a conflict, where a PVC and the according StorageClass have different configurations, I see the following solutions:
- Enforce the configuration set in StorageClass (enforcing)
- Override configurations of StorageClass by the ones in PersistentVolumeClaim (default values)

I would prefer the first solution, as this can be used to enforce policies and if someone would like to have default values, he/she can use Kubernetes templates.

Kind regards
Boris

**Comment by adkerr** [comment]
Tracked internally by [US2431](https://rally1.rallydev.com/#/47479883219d/detail/userstory/112144057776)

**Comment by kangarlou** [comment]
Hi. We have intentionally kept storage class definitions generic so that they can be used across the three NetApp platforms (i.e., ONTAP, SolidFire, and E-Series). We may revisit this decision later if there is a compelling use case.

As you mentioned, it's not possible to define the export policy via storage classes, but if all volumes from a given ONTAP backend are going to have the same export policy, an admin can define the default policy in the backend definition. See the "defaults" section in the backend definition: https://github.com/NetApp/netappdvp/blob/master/docs/install/ndvp_ontap_config.rst#example-ontap-config-files.

A user can still overwrite the admin-defined export policy via the PVC annotation. The team at NetApp is considering which options can be overwritten by the users or not, so we appreciate any input you might have. You need to use Trident 17.04.0 or later to take advantage of this feature.

**Comment by kincl** [comment]
@kangarlou your answer did fix my problem, thank you! It might be good to add that note about the "defaults" section to docs here in Trident because if I had missed this issue I would not have figured out how to set defaults for a backend.

Thanks!

**Comment by kangarlou** [comment]
Great! We're planning to add a new section to the docs that captures best practices for writing Trident storage classes . That section should capture what should be set via storage class parameters, backend defaults, or PVC annotations.
