### ISSUE TITLE
Deal with deleted data captured in snapshots

### ISSUE THREAD

**Issue by cgajan** [NetApp/trident#242]
ontap-nas-economy driver need new parameters to allow autogrow on trident_qtree_pool_* volume
The current behavior for trident_qtree_pool_* volume resizing is not satisfying (size of volume = sum of hosted qtrees)
Use case: 

- create a new 1G PV this create new volume of 1.2 GB (20% of snap reserve) which host the new 1G qtree
- fill the PV with 0.8 GB of data
- take a snapshot on the trident_qtree_pool_* volume (done automatically via the snapshot policy)
- remove the data
- try to fill the PV with 0.5 of data --> you get a no more space on device error

When a trident_qtree_pool volume host a small amount of qtree quota, the volume is small and the snapreserve too
So it is easy to get file system full when few small PV are hosted in a trident_qtree_pool volume
This effect is less frequent/possible when the volume is bigger.

A simple possible solution for such issue is to set autogrow on the trident_qtree_pool
In this case is no more needed to resize the volume each time a qtree is added
The volume size should be controled via a "max-autosize" parameter

Note that such filesystem full issue can also has effect during a PV deletion
```
time="2019-04-19T08:05:01Z" level=error msg="Qtree rename failed. API status: failed, Reason: Failed to rename qtree \"RES_B1P1S1N1C0E0_proj1_mysql_claim_254d6\" for volume \"trident_qtree_pool_RES_B1P1S1N1C0E0_YYWQMEMSFO\" on Vserver \"svm01\". Reason: Filesystem access error: No space left on device., Code: 13114"
time="2019-04-19T08:05:01Z" level=error msg="Unable to delete volume from backend." backend=R1_B1_P1_S1_N1_C0_E0_svm01 error="volume deletion failed" volume=proj1-mysql-claim-254d6
time="2019-04-19T08:05:01Z" level=error msg="Kubernetes frontend failed to delete the volume for PV proj1-mysql-claim-254d6: volume deletion failed. Will eventually retry, but volume and PV may need to be manually deleted."
```

**Comment by innergy** [comment]
Obviously they can also wait until the snapshots that are holding their deleted data roll off.

This issue isn't specific to the economy driver. Any volume can have its free space stranded in deleted data residing in snapshots. The economy driver is potentially impacted by this more because that snapshot data is shared across many volumes, so another common resolution (deleting the snapshots) may not be viable.

We'll have to discuss this one a bit more before settling on an appropriate resolution. Many admins won't want volumes chewing up any more space than they're "paying" for.

**Comment by gnarl** [comment]
This issue was addressed in commit [e824af](https://github.com/NetApp-openstack-dev/trident/commit/e824af514b921362f7963b6f0b504d976c0e2362).
