### ISSUE TITLE
The files are getting created and owned by "nobody"

### ISSUE THREAD

**Issue by beth2016** [NetApp/trident#269]
The files are getting created and owned by "nobody:.  
Any chown command results to "permission denied".   Is there any setting we need to add to get the files to be owned by root?

**Comment by korenaren** [comment]
Hi @beth2016 can you provide more details? What version of Trident? Which driver? What are you doing to get in this situation? May need to direct you to NetApp Support on this one, but we can try to help if you can provide some more context. Thanks!

**Comment by nareshkumargunjalli** [comment]
I think this issue is seen on the **"ontap-nas"** driver..
If ontap-nas* driver, then this issue(not an issue rather an expected behavior) will be seen because of "**root_squash**" option being enabled on the NFS server(Data ONTAP).

It is necessary for the "**root_squash**" to be enabled on the NFS servers.
When "**root_sqaush**" is enabled all the files created by root user(on the client) will be downgraded to a 
underprivileged user account "nobody" on the nfs server, which prevents uploading of programs with the setuid bit set.
If "**no_root_squash**" is used, remote root users are able to change any file on the shared file system 
and leave applications infected by Trojans for other users to inadvertently execute.

Only the files created by a "root" user on the client will be assigned as "nobody".
If the files are created on the client using any other user like "usera", then the "user" and "group" properties will not be modified.

@beth2016 Did you try creating files using any other user other than root and observe the similar behavior?

**Comment by beth2016** [comment]
@nareshkumargunjalli 
Thanks for the info.   non root users worked as you described.  But we have situations where we need to to work as root as well.   Can this be configurable to support both use cases?

**Comment by nareshkumargunjalli** [comment]
Hello @beth2016 

You can create a new export policy and rule for it or modify the existing export-policy rule to support this.

For disabling root-squash, the **ONTAP export policy rule** should be created/modified by setting the **"superuser" param to sys/any.**
**This export policy(whose export-policy rule has superuser set to sys/any) should be associated to the ONTAP volume which acts as a PV.**
For the already provisioned volumes, modify the export policy on the volume to the newly created policy, it should work.

I created a new export-policy with following config..

- _export-policy create -vserver svm1 -policyname policy_with_no_root_squash_
- _export-policy rule create -vserver svm1 -policyname policy_with_no_root_squash -clientmatch 0.0.0.0/0 -rorule any -rwrule any -superuser sys_

For the new pvc's I had set the default export policy in the backend config..
Then I created a new backend for this svm and specified the default export-policy to be used for volumes being provisioned in this svm.
**sample_backend.json**
_{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "clus3",
    "managementLIF": "xx.xx.xx.xx",
    "dataLIF": "xx.xx.xx.xx",
    "svm": "svm1",
    "username": "usera",
    "password": "*******",
    "defaults": {
      "exportPolicy": "policy_with_no_root_squash"
    }
}_

When I provision a new pvc on this backend and mount it on a running pod I can create files with root permissions.
Hope this helps.. Let me know if you need more details.

**Comment by beth2016** [comment]
@nareshkumargunjalli,  thank you so much.  That works.
