### ISSUE TITLE
Making trident take parameters/annotations from PVC, for creating a corresponding PV that points to a specific endpoint

### ISSUE THREAD

**Issue by Sanjary** [NetApp/trident#30]
A single and same NFS share can be declared in multiple PVs and a corresponding PVC can use that. But if we want it in trident way, then trident creates a random PV with non-deterministic endpoint. So, I think it will be a nice to have feature to pass the NFS server and path as annotation or something so that trident creates the PV accordingly. Is anyone working on any similar thing?

PS. This can be for any storage that supports RWX access mode.

**Comment by kangarlou** [comment]
Trident's main function is to provision new storage, which entails creating a volume on the storage backend and creating the corresponding PV. What you're asking can easily be accomplished by reusing PVCs. For example, you have a PVC called pvc-bronze that gets bound to a PV that is either statically or dynamically provisioned. Once this PVC is bound, you can have multiple pods referring to the same PVC and consequently accessing the same volume. There is no need for Trident or the admin to create a new PV that points to the original volume.

**Comment by Sanjary** [comment]
I agree but my use case is different. I want to acess same pv endpoint from multiple namespace/projects. The I can not re use the pvc in multiple pods in multiple namespaced/projects. Because, pvcs are namespaced/project based. Then thi requirement arises.

**Comment by kangarlou** [comment]
Your use case does change things, but I should note that PV details are not necessarily exposed to users. For example, in OpenShift, regular users don't have enough privilege to get the details of a PV, so they can't supply that information using a PVC to Trident. 

I admit that this type of cross-namespace workflow hasn't been not considered well in Kubernetes. I've had discussions with members of the community around this issue, particularly as it relates to snapshots, but as I said, there is no good solutions for it now. We can change Trident to create multiple PVs, all pointing to the same volume on the storage backend, and have Trident create the corresponding PVCs in different namespaces, but this type of capability, if not implemented carefully, can potentially cause security concerns, especially for preexisting PVs that shouldn't be accessed across namespaces. One way to alleviate security concerns is to have a Trident-specific annotation in the PVC and in the corresponding Trident-provisioned PV that would allow the PV to be duplicated and accessed across different namespaces. By default, this property should be turned off. In this proposed design, the user doesn't supply the details of the PV in PVC, but instead specifies the namespace(s) where that volume should be accessed. Trident would then create one PV per namespace and the matching PVC pre-bound to those PVs. 

The proposed workflow works well for accessing newly created volumes from multiple namespaces, but accessing a preexisting volume from a different namespace is somewhat different and requires a slightly different workflow. Do you expect to access newly created volumes across namespaces or preexisting volumes? Also, how often do you expect that cross-namespace volumes get created in your environment?

**Comment by Sanjary** [comment]
My use case follows this flow: user does not provide/create this pvc/pv. Uses a template that does this for the user. Also I do not need this endpoint for my pv in all namespaces, only in those where this particular type of app is deployed using the template and the template should create the pvc and pv. I was hoping in this scenario if I can pass some kind of annotation with the server and path for a pre existing volume to the pvc object creation inside the template and if trident could just create a new pv inside the namespace with the given server and path in pvc annotation and bind the pv with a pre existing endpoint to the pvc, then it would simplified the workflow of templating my app to a decent extent.

**Comment by Sanjary** [comment]
Just want to add a bit more of my concern here. For this template to be execute by a dev, I need to give the devs a special custom cluster role like PV-creator which can only create pv and unable to do anything else. But if an annotation can take care of it with the help of trident, then I can get rid of the PV creation handling part and trident can handle the rest.

**Comment by kangarlou** [comment]
I think my previous comment addressed all your concerns. 

> user does not provide/create this pvc/pv. Uses a template that does this for the user

PVC would be the template through which a user can create PVs pointing to the same volume in different namespaces.

> Also I do not need this endpoint for my pv in all namespaces, only in those where this particular type of app is deployed using the template and the template should create the pvc and pv.

My earlier comment address this concern: "the user doesn't supply the details of the PV in PVC, but instead specifies the namespace(s) where that volume should be accessed from. Trident would then create one PV per namespace and the matching PVC pre-bound to those PVs."

> I was hoping in this scenario if I can pass some kind of annotation with the server and path for a pre existing volume to the pvc object creation inside the template and if trident could just create a new pv inside the namespace with the given server and path in pvc annotation ...

As I said,  "PV details are not necessarily exposed to users. For example, in OpenShift, regular users don't have enough privilege to get the details of a PV, so they can't supply that information using a PVC to Trident." In the case of NFS, one can get NFS share details by running mount in the pod, but in general users don't have any knowledge of the PV (only admins can run `kubectl describe pv` and get the details of the PV).

> For this template to be execute by a dev, I need to give the devs a special custom cluster role like PV-creator which can only create pv and unable to do anything else.

For the proposed solution that I outlined, there is no need to give devs special privileges.

It seems that you want to access a volume **after** it has been provisioned from a different namespace as opposed to having Trident expose a volume to different namespaces at the time of provisioning. Is that correct?

**Comment by asteven** [comment]
I also need to reuse the same volumes in multiple namespaces.
Is there an easy way to do that these days?

**Comment by balaramesh** [comment]
@asteven I can share some context here related to your ask. Kubernetes expects volumes to be namespaced. Said differently, PVCs are namespaced. There are a couple of approaches to sharing/exposing volumes across namespaces:

1. User creates a PVC in namespace A, Trident creates a PV and exposes it for an application in the same namespace. To consume the same volume in namespace B, you can statically define a PV that references a pre-existing volume created by Trident.
2. Alternatively, the storage admin can create a volume on the storage cluster and have the k8s admin/SRE create PVs in the desired namespaces. This way, the volume is created without an associated PVC.

**Comment by asteven** [comment]
@balaramesh Thanks for the answer. I know how to do this by hand. The question was if trident gives me some sugar here ;-)
Guess that's a no. No Problem.
:wave:

**Comment by balaramesh** [comment]
@asteven you are right there isn't a way to achieve this natively through Trident right now

**Comment by candidoma** [comment]
Hi,
we need to share the same image in different namespace without cloning/snapshot it.
I tried, as suggested before, to copy the original pv/pvc and run a pod using the new pvc.
What i did is the following:
1) Create a Deployment with a pvc in the namspace X
2) When pods are up&running copied the pvc and pv into a yaml file.
3) Change pvc and pv name and their references between them.
4) Apply the new pvc/pv to the cluster in the namespace Y
5) They were bounded together
6) Create a 2nd Deployment in the namespace Y
7) Pods remaining in "Container Creating" status and the error is : _MountVolume.SetUp failed for volume "pvc-nginx-nfs-pvc-clone" : rpc error: code = FailedPrecondition desc = staged device info file not found_

Any modification to the pvc/pv doesn't change anything...
From the trident pod i can see the following log:
`trident-main time="2021-12-16T14:59:33Z" level=error msg="Unable to find staged device info." error="stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-nginx-nfs-pvc-clone/globalmount/volumePublishInfo.json: no such file or directory" requestID=f687d4c1-89f6-48de-b64e-52acd9f5dbf7 requestSource=CSI stagingTargetPath=/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-nginx-nfs-pvc-clone/globalmount/volumePublishInfo.json                                                                                                                                                                                                   
trident-main time="2021-12-16T14:59:33Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = staged device info file not found" requestID=f687d4c1-89f6-48de-b64e-52acd9f5dbf7 requestSource=CSI `

What i can understand is that the trident plugin is trying to find a json file in a path on the node where the pod is running.
But it's unable to find it, because the file is under the path **/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-c3d33062-d0db-48b6-9ee5-2d2ba24dd234/globalmount/volumePublishInfo.json ** that is the path for the pv in the namespace X.

If i stop the pods on the namespace X , the pods in the namespace Y are working.

So there's a way to use the same pv between different namespace using nfs netapp storage?

Thanks in advance.
