### ISSUE TITLE
Support for Kubernetes 1.17

### ISSUE THREAD

**Issue by gprossliner** [NetApp/trident#327]
Hello everyone!

Thank you for providing this useful tool as OpenSource. We use it in production, to integrate our NetApp storage infrastructure into Kubernetes.

We want to upgrade your Development Cluster to Kubernetes 1.17. Basically to enable the new [Service Topology](https://kubernetes.io/docs/concepts/services-networking/service-topology/) feature for testing.

As trident is documented to support Kubernetes 1.16 at max, I want to ask:
* Is it really not compatible, or is it not tested to work against 1.17?
* It there any plan to support 1.17 in the near future?
* How to you integrate new Kubernetes versions in general? Is there a kind of policy for this?

If you need further information, please let me know.
If you want me to help on this Issue, I would appreciate it.

**Comment by korenaren** [comment]
Hi @gprossliner - the installer has a version limiter to prevent installing Trident in a version of Kubernetes that we couldn't test (because it wasn't available at time of Trident release). In other words, we don't support forward compatibility. The Trident 20.01 version (to be released in January) will support 1.17. Our goal is to always provide new versions of Kubernetes in the closest Trident release as possible.

**Comment by gprossliner** [comment]
Hi korenaren - thank you for this incredible fast response! If it is included in the v20.01 version, this would be perfect. Thanks

**Comment by lucidqdreams** [comment]
we just tried to install 20.01 on 1.17 and got a version limit still.  So are you planning to change this in the future or should it be working now?


![image](https://user-images.githubusercontent.com/6086602/72095184-db2b8100-32cc-11ea-86e0-e37cc46c6bc9.png)

**Comment by korenaren** [comment]
The 20.01-beta did not have support for 1.17. Sorry. But we are planning to support at 20.01 final release.
