### ISSUE TITLE
Azure NetApp Files is hardcoded to use NFS v3 when creating Kubernetes / OpenShift volumes

### ISSUE THREAD

**Issue by nccurry** [NetApp/trident#334]
When configuring trident against Azure NetApp Files the volumes created in Azure will always be NFS v3, regardless of whether or not the trident backend contains ```-o nfsvers=4``` for nfsMountOptions.

It appears this is hardcoded in the NFSStorageDriver.Create() method here:
https://github.com/NetApp/trident/blob/master/storage_drivers/azure/azure_anf.go#L533

**Comment by gnarl** [comment]
Unfortunately, Azure does not support NFS v4. Once Azure supports NFS v4 we will remove this hardcoded restriction from Trident.

**Comment by nccurry** [comment]
https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-create-volumes

> Azure NetApp Files supports NFS (NFSv3 and NFSv4.1) and SMBv3 volumes.

**Comment by gnarl** [comment]
@nccurry, you're right. Thanks for pointing this out. It looks like it currently requires a whitelisting step according to this https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-faqs.

**Comment by paulomarquesc** [comment]
Hi @gnarl, I'm from Azure NetApp Files team (MSFT side), NFSv4.1 is GA and does not require whitelisting anymore, can someone from your team make this setting pointed out in the snippet @nccurry referred here to accept both NFSv3 and NFSv4.1? If that helps, I recently published our [ANF SDK sample for Go](https://github.com/Azure-Samples/netappfiles-go-sdk-sample) so you can take a look on how I'm creating NFSv4.1 volumes. Also, please let me know if you need my help on this to speed up fixing this issue since we have another customer in need for NFSv4.1 implemented on Trident.

**Comment by gnarl** [comment]
Hi @paulomarquesc,

Our release schedule is every three months with the next release (20.04) being sometime in April. We will try to fit this change into the release schedule. Thanks for notifying us by updating the issue.

**Comment by gnarl** [comment]
@paulomarquesc is Trident now able to set both NFSv3 and v4 at volume create time for ANF? This was previously a limitation that led us to hardcoding only support for NFSv3. I am @fchuck on [thePub Slack](https://netapp.io/) if you want to contact me directly.

**Comment by paulomarquesc** [comment]
@gnarl, ANF supports both (plus SMB), and NFSv4.1 (which is now GA). Yes, I understand why it was hard-coded but now you can allow one of the protocols (not both at the same time on same volume). I just joined the Slack channel.

**Comment by clintonk** [comment]
This was resolved in the 20.07.0 release.  6a4f3d101dcfa858f929d200446032cac470674b
