### ISSUE TITLE
sample-input/storage-class-bronze.yaml is missing from the docs

### ISSUE THREAD

**Issue by andiMenge** [NetApp/trident#34]
Hi,
in the `README.md` the folder `sample-input` is referenced multiple times. But the folder is missing from the repo (at least I am unable to find it).

Without the samples it's difficult to write a valid trident storageclass for the solidFire backend.

Best regards,
Andi

**Comment by adkerr** [comment]
https://github.com/NetApp/trident/tree/master/trident-installer/sample-input

**Comment by andiMenge** [comment]
that was fast. Thx

**Comment by adkerr** [comment]
No problem :)

**Comment by kangarlou** [comment]
Hi. The instructions refer to the sample-input directory that is included in the Trident installer bundle for each release (e.g., [trident-installer-17.07.0-beta.1.tar.gz](https://github.com/NetApp/trident/releases/download/v17.07.0-beta.1/trident-installer-17.07.0-beta.1.tar.gz).)

You should do step 5 before you do step 6:

> 5. Download and untar the Trident installer bundle. Then, change into the trident-installer directory resulted from untar.

So you don't have to clone the GitHub repo to access these sample files; you just have to donwload the installer.

**Comment by andiMenge** [comment]
@kangarlou I followed the `Deploying As a Pod` instruction and built it from src with custom k8s manifests. Maybe that was a not so good idea....

**Comment by kangarlou** [comment]
Yes, I recommend that you use the installer bundle because the installer does a lot of things in the background (e.g., creating a volume for Trident itself, creating service accounts, RBAC roles, etc.). Here is the most recent installer:  [trident-installer-17.07.0-beta.1.tar.gz](https://github.com/NetApp/trident/releases/download/v17.07.0-beta.1/trident-installer-17.07.0-beta.1.tar.gz)
