### ISSUE TITLE
tridentctl should have a flag to provide path to kubeconfig

### ISSUE THREAD

**Issue by pknutti** [NetApp/trident#347]
**Describe the solution you'd like**
It would be nice to have a flag like it is already available in kubectl to provide a path to a kubeconfig file.

**Describe alternatives you've considered**
An alternative could be to install trident without tridentctl for example as YAML for kubectl. But this does not work at the moment because there is no possibility to get all required files used by tridentctl

**Additional context**
Currently it is hard to provide trident via helm and because of this I am using a pipeline to install it. But for this I have to use a dedicated runner (GitLab docker runner instead of the default kubernetes runner) because tridentctl uses the wrong credentials all the time. With kubectl all works fine :/

**Comment by Aracannan** [comment]
yes it's really something that is missing at the moment because without it it's very complicated to automate the installation of Trident.
A flag for a custom kubectl path would also be nice.

**Comment by gfvirga** [comment]
I just ran into this problem. I use gitlab ci/cd pipeline. I fed the kubeconfig via variable, but the tridentctl is trying to use the gitlab-runner service account to deploy. The runner is not even in the same cluster.

**Comment by pknutti** [comment]
@gfvirga If you need a workaround: Try using docker runner and use KUBECONFIG variable (export KUBECONFIG=<Path_to_kubeconfig>). This is how I got it to work. 

Anyway I want to have a feature like a kubeconfig flag to use one runner for all of my projects and not a dedicated one for trident :/ .

**Comment by gnarl** [comment]
The [remote install](https://netapp-trident.readthedocs.io/en/stable-v20.01/dag/kubernetes/deploying_trident.html#trident-installation-modes) section of the documentation does state to set the KUBECONFIG env variable. We will update the documentation to indicate that any use of tridentctl needs the KUBECONFIG env var set if the kube config is not in the expected location.

**Comment by gfvirga** [comment]
We have the kubeconfig variable exported. When running this command in gitlab pipelines in a kubernetes container it will use the serviceaccounttoken (https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) instead of the kubeconfig. If there will be a helm chart for this in the near future, I will stop trying to use tridentctl in gitlab pipelines.
There is also a ticket with gitlab to allow the runner to start containers without the serviceaccounttoken - https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/1350

**Comment by gnarl** [comment]
The documentation for Trident 20.04 was updated in additional sections to indicate that the KUBECONFIG variable should be set when using tridentctl.
