### ISSUE TITLE
Install Snapshot CRDs & Snapshot Controller for K8s 1.17 or higher

### ISSUE THREAD

**Issue by pablogarciaarevalo** [NetApp/trident#351]
**Issue description**
With K8s 1.17 the Snapshots are moving from alpha to beta and there are a lot of changes in the CSI. One change is that K8s requires to install the Snapshot Beta CRDs and the Snapshot Controller (https://kubernetes-csi.github.io/docs/snapshot-controller.html#deployment).

**Improvement**
It would be very easy for Trident to check in the installation phase (https://github.com/NetApp/trident/blob/master/cli/cmd/install.go) the K8s release and apply the required yaml files if the K8s version is 1.17 or higher.

**Comment by korenaren** [comment]
See our blog here: https://netapp.io/2020/01/30/alpha-to-beta-snapshots/

**Comment by pablogarciaarevalo** [comment]
Yes, I did read the blog. But as far as I understand and I have been said the beta CRDs and the snapshot-controller needs to be created manually before install Trident 20.01 or above. I'd like to see Trident checking the K8s version and creating the CRD and snapshot-controller by itself.

**Comment by adkerr** [comment]
@pablogarciaarevalo That behavior is essentially what the alpha snapshot sidecar used to do for us. The Kubernetes community decided that it is not the place of the sidecars or storage provisioners to be adding these CRDs or controllers, especially while in alpha/beta state; this should need be explicitly enabled by the Kubernetes admin. Thus it is the responsibility of the admin or Kubernetes distribution to install these components themselves if they wish for the functionality to be enabled.

Having the alpha CRDs be auto-installed actually did get us into trouble, since they are not compatible with the beta versions and must be completely removed from the cluster before you can properly use beta level snapshots. This means that users who never wanted or intended to use the snapshots while in alpha are still stuck having to remove these components when upgrading. So, again, to avoid this we're requiring that admins, or distros, handle the installation of the CRDs and controller moving forward.

**Comment by pablogarciaarevalo** [comment]
Understood. Thanks a lot for the detailed answer.
