### ISSUE TITLE
debug mode enabled on a fresh 20.04 install

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetApp/trident#395]
**Describe the bug**
The documentation states that the default value for the Operator's "debug" parameter is 'false'.
However, debug mode is enabled anyway.

**Environment**
- Trident version: [e.g. 19.10] 20.04

**To Reproduce**
Look in the _deploy/bundle.yaml_ file or the _deploy/operator.yaml_ file for the _command_ parameter:
```
          command:
          - "/usr/local/bin/trident-operator"
          - "--debug"
```
or the TridentProvisioner description in a default/fresh install:
```
Spec:
  Debug:  true
```

**Expected behavior**
Consistency between documentation & deployment package

**Comment by ntap-arorar** [comment]
Hi @YvosOnTheHub: TridentProvisioner's debug value installs Trident in debug mode not the Trident Operator.

This installs the Trident Operator in debug mode.
`command:
          - "/usr/local/bin/trident-operator"
          - "--debug"
`

This tell Trident Operator to install Trident in debug mode, this defaults to false.
`Spec:
  Debug:  true
`

**Comment by YvosOnTheHub** [comment]
ok for the operator part.

However, Trident was installed with _debug_ enabled by default
the "Spec: Debug: True" was automatically set during the installation, which was completly standard.

this is what I got immediatly after installing Trident:
```
[root@rhel3 trident-installer]# kubectl describe tprov trident -n trident | grep Spec: -A 5
Spec:
  Debug:  true
Status:
  Message:  Trident installed
  Status:   Installed
  Version:  v20.04
```
This link also shows _Debug:True_
https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/operator-install.html#creating-a-tridentprovisioner-cr-and-installing-trident

Said differently, I had to patch the provisioner to disactivate debug mode, where I was expecting the opposite, ie patch the provisioner to activate debug mode

**Comment by gnarl** [comment]
@YvosOnTheHub I can understand your expectation that debug should be off by default. The majority of our support cases though are related to the installation and the debug logs are needed in those cases to resolve customer issues. With the Operator, you are able to easily turn debug mode on or off compared to how you could only set the debug mode using the tridentctl install previously. 

Considering this we would like to keep debug mode on by default in order to better assist customers that encounter problems. We are planning on updating the Status section of the CR to reflect all settings, including default settings, in the Trident 20.07 release so that this should be apparent to the end-user.

**Comment by YvosOnTheHub** [comment]
got it
thank you @gnarl
