### ISSUE TITLE
Removal of IQNs from NetApp when using Trident on OCP 3.11

### ISSUE THREAD

**Issue by sbarre-esit** [NetApp/trident#463]
**Describe the bug**
When upgrading from v20.04.0 to v20.07.0 or 20.07.01 on a non-CSI kubernetes Trident removes all the IQNs from the igroup causing all persistent volumes to fail.

It appears a commit was made directly to `master` with no associated issue or pull request https://github.com/NetApp/trident/commit/41f39bcc48db6c5b40d6e8c801cc7603a84b5528 that introduced this code.

It also appears that despite OCP 3.11 being listed in the docs as a supported platform, it was not tested with Trident v20.07.0 before release.

**Environment**
- Trident version: 20.07.x
- Trident installation flags used:  -n trident --silence-autosupport
- Container runtime: Docker
- Kubernetes version: v1.11.0+d4cacc0
- Kubernetes orchestrator: OpenShift v3.11
- Kubernetes enabled feature gates: none
- OS: RHEL 7.8
- NetApp backend types: ONTAP Select

**To Reproduce**
Upgrade Trident
Attempt to launch a pod that uses a ontap-san or ontap-san-economy driver

**Expected behavior**
Volumes to be accessable

**Additional context**
It appears this issue was also reported on Slack on Oct 1st. I would appreciate if in the future major bugs like this could be made more public somehow? Perhaps update the release notes with known issues? or ensure a issue is created in GitHub to track these things?

I'd also like to see better code development practices. A single commit directly to master seems like poor form.

**Comment by gnarl** [comment]
Hi @sbarre-esit,

The Trident team uses a private GitHub repository for development work. The PRs exist in that repository. After the commit to master passes the CI the commit is pushed to master on the public repository. 

OpenShift 3.11 is being tested in a single node environment in our CI which is why this issue wasn't caught by the CI. We already have a fix internally for this issue and it will be included in the Trident 20.10 release.

**Comment by adkerr** [comment]
Resolved in 9751a1ee8cd42fd630e01aa099dd2a22c4eead94

**Comment by gnarl** [comment]
This issue was fixed with the Trident v20.10 release.
