### ISSUE TITLE
The Azure NetApp Files Backend should not report "online" upon receiving invalid credentials.

### ISSUE THREAD

**Issue by carlosonunez** [NetApp/trident#465]
**Describe the solution you'd like**
As of v20.04, the Azure NetApp Files backend will report itself as being `online` even if its `backend.json` contains invalid credentials. The backend should report itself as being `offline` or `failed` in this scenario.

**Describe alternatives you've considered**
The current workaround is to initialize the backend with `tridentctl create backend` and then attempt to provision a volume through a `PersistentVolumeClaim` or wait for capacity pool discovery to take place.

**Additional context**

I'm working on a pull request that addresses this. Fork is at github.com/carlosonunez/trident. A link to the pull request will be submitted in the comments!

**Comment by balaramesh** [comment]
@carlosonunez can I ask you to clarify what "invalid credentials" means here? The reason I ask this is: ANF backends need 4 parameters to identify the ANF subscription that it needs to provision vols against: `clientID`, `subscriptionID`, `tenantID`, and `clientSecret`. If the parameters have an incorrect/false value provided in the backend definition, Trident will be able to catch that since calls to the Azure SDK will fail. Please correct me if I am wrong here.

Based on what was explained above, it looks like the real problem would be the access permissions for the app registration (whose credentials are passed with `clientID`, `clientSecret`). It could be that an app registration with insufficient permissions leads to a backend being created successfully, but it really doesn't have the ability to fetch virtual networks/capacity pools for example. The Trident logs will contain references to that. For example, "No Capacity Pools Found". 

Can you share the error message you observed when you tried to create a PVC on a backend that was reported online?

**Comment by carlosonunez** [comment]
@balaramesh , thanks for getting back to me. What I mean by the PR here is that I should see that I have invalid credentials or some other issue authenticating into Azure before I attempt to create a backend with `tridentctl`. While you are correct in that one will eventually see vols fail to get created due to HTTP 401s or HTTP 403s in the chain, it's not immediately obvious when this happens. In my case, it lead to a confusing user experience.

Unfortunately I no longer have a screenshot of the error that I received, as I'm no longer working with the client using this provisioner. However, I did raise an issue with NetApp support at the time and referenced this issue and the pull request associated with it in that ticket. You might have better luck searching for the originating error internally.

I hope that helps!

**Comment by gnarl** [comment]
This issue is fixed with [commit 809f0d4](https://github.com/NetApp/trident/commit/809f0d4a2a2ed771e6302d1b2f7fb0c16f32981e) and will be included in the Trident 22.01 release. The ANF storage driver will discover if the backend credentials are invalid during driver initialization.
