### ISSUE TITLE
storagePrefix from backend.json is ignored with a SolidFire Backend

### ISSUE THREAD

**Issue by andiMenge** [NetApp/trident#48]
# Problem
The `storagePrefix` in my `backend.json` config for SolidFire is not prepended to the volumes in the backend.

## Details
- API `9.3`
- Trident `17.07.1`

```
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "storagePrefix": "ucpTrident",
    "Endpoint": "<censored>",
    "SVIP": "<censored>",
    "TenantName": "<censored>",
    "InitiatorIFace": "default",
    "AccessGroups": [1],
    "Types": [{"Type": "slow", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "default", "Qos": {"minIOPS": 4000, "maxIOPS": 6000, "burstIOPS": 8000}},
              {"Type": "fast", "Qos": {"minIOPS": 6000, "maxIOPS": 8000, "burstIOPS": 10000}}]
}
```

solidfire-volume-details
<img width="331" alt="solidfire-volume-details" src="https://user-images.githubusercontent.com/12414526/28933311-e9937d72-787c-11e7-9fba-d538c4cefd78.png">

**Comment by dutchiechris** [comment]
Hi @andiMenge 

The actual logic Trident uses to create and destroy storage on the backend arrays is imported from the NetApp Docker Volume Plugin (nDVP).  In nDVP the storagePrefix field ensures that dynamically provisioned storage is not confused with manually provisioned storage.  For ONTAP backends with a SVM shared for multiple purposes it can be quite useful.  With SolidFire though it's unnecessary because all volumes exist within an Account defined in the `TenantName` field in the nDVP/Trident backend config.  

So to segment storage with ONTAP you can use `storagePrefix` (and SVMs if you want), but with SolidFire you use multiple accounts defined using `TenantName` to do the same.

In an earlier version of nDVP storagePrefix was used with SolidFire too but as part of work done in 
https://github.com/NetApp/netappdvp/pull/58 it was depreciated.  I think the Trident documentation has never been updated.

Trident devs, did I get this right and a Trident doc update is needed?

**Comment by kangarlou** [comment]
@dutchiechris Your comment is accurate. We need to update README and the sample input files as the `storagePrefix` field has been deprecated for SolidFire.
