### ISSUE TITLE
fsGroupPolicy not set with k8s 1.20

### ISSUE THREAD

**Issue by jscott0918** [NetApp/trident#527]
**Describe the bug**
A pod is failing to deploy because fsGroupPolicy is not set for a PVC which is preventing the use of the pvc. The pod never deploys and throws errors while Creating due to unset fsGroupPolicy.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.10.0
- Trident installation flags used: [e.g. -d -n trident --use-custom-yaml]
- Container runtime: 20.10.2
- Kubernetes version: 1.20
- Kubernetes orchestrator: kubeadm deployed with Kubespray
- Kubernetes enabled feature gates:
- OS: RHEL 7.6
- NetApp backend types: ONTAP AFF 9.8P1
- Other:

**To Reproduce**
Using Kubestone Getting Started guide: https://kubestone.io/en/latest/quickstart/
Deploy a generic ONTAP backend (Flexgroup) and storage class.
Deploy an FIO test with PVC using Kubestone with volume reservation as part of the deployment definition.

**Expected behavior**
FIO test pod should deploy successfully, run to completion, and terminate.

**Additional context**
I am able to mount the flexgroup manually from my nodes.

>Events:
>  Type     Reason       Age                   From     Message
>  ----     ------       ----                  ----     -------
>  Warning  FailedMount  56m (x107 over 19h)   kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[default-token-jtv49 data]: timed out waiting for the condition
>  Warning  FailedMount  7m2s (x593 over 19h)  kubelet  MountVolume.NewMounter initialization failed for volume "pvc-6b94932f-724d-4c7d-a0ce-e40f881cfcde" : kubernetes.io/csi: expected valid fsGroupPolicy, received nil value or empty string
>  Warning  FailedMount  109s (x417 over 19h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data default-token-jtv49]: timed out waiting for the condition

**Comment by ffilippopoulos** [comment]
@jscott0918 I saw that when accidentally had components running on kube 1.19.2 (apiserver, controller manager and scheuler) but a few nodes running kubelet 1.20.2. Those nodes were unable to mount pvcs with the same error you posted.
I believed that it's due to feature gate `CSIVolumeFSGroupPolicy` that becomes beta on 1.20 (which almost always mean enabled by default)
https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/#allow-csi-drivers-to-declare-support-for-fsgroup-based-permissions
In my case rolling master components to kube 1.20 was enough to get things going again.

**Comment by balaramesh** [comment]
@jscott0918 by default, `fsGroupPolicy` is set to `ReadWriteOnceWithFSType` for the Trident `CSIDriver` on Kubernetes 1.20. I was able to confirm this in my environment which had Trident `v21.01.1` installed.

```
 k get csidriver -o yaml
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: CSIDriver
  metadata:
    creationTimestamp: "2021-04-19T16:24:41Z"
    managedFields:
    - apiVersion: storage.k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:attachRequired: {}
          f:fsGroupPolicy: {}
          f:podInfoOnMount: {}
          f:volumeLifecycleModes: {}
      manager: kubectl-create
      operation: Update
      time: "2021-04-19T16:24:41Z"
    name: csi.trident.netapp.io
    resourceVersion: "1096"
    uid: 357d9d50-5210-4282-a500-00d9e5cd89f2
  spec:
    attachRequired: true
    fsGroupPolicy: ReadWriteOnceWithFSType
    podInfoOnMount: false
    volumeLifecycleModes:
    - Persistent
```
In your case, the problem is caused by running Trident `20.10.0` on Kubernetes `1.20`, which is an unsupported Kubernetes version

**Comment by gnarl** [comment]
Per @balaramesh's post, upgrading Trident to 21.01.2 will fix this issue.
