### ISSUE TITLE
Document how to upgrade from 21.01+ to 21.04

### ISSUE THREAD

**Issue by cprivite** [NetApp/trident#579]
**Describe the solution you'd like**
You currently have no documentation for upgrading from 21.01 to 21.04. Everything in the documentation presumes you're either using helm or are upgrading from 20.07 or earlier (so it walks you through migrating to the new orchestrator). If you're already on the orchestrator, there's no documentation on how to upgrade.

**Comment by balaramesh** [comment]
@cprivite thank you for opening this issue. While we add this to the docs, here is what you will need to do if upgrading from version A to version B:

1. Delete the existing Trident operator using its `bundle.yaml` file. For example, if A is 21.01, you will need to execute `kubectl delete -f 21.01/trident-installer/deploy/bundle.yaml -n trident`
2. [OPTIONAL] Update the install parameters if required. This would require editing the `TridentOrchestrator` object that you had created when installing version A (21.01)
3. Install version B (21.04) using the `bundle.yaml` file that sets up the Trident operator for version B. In your case, you will need to execute `kubectl install -f 21.04/trident-installer/deploy/bundle.yaml -n trident`. As part of this step, the 21.04 Trident operator will identify an existing `TridentOrchestrator` and upgrade it to the same version as the operator.



Please let me know if you have any questions. As stated earlier, the documentation will be fixed in parallel.

**Comment by cprivite** [comment]
Thanks, I actually ended up just uninstalling the orchestrator and installing via helm. Was surprised how seamlessly and non-disruptive that was. Thanks for making good code!

**Comment by gnarl** [comment]
This documentation issue is fixed with the Trident 21.04.1 release.
