### ISSUE TITLE
Base install instructions on non-default namespace

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#61]
It appears that https://github.com/NetApp/trident#getting-started is based on trident being in the default namespace:

"When the installer completes, `kubectl get deployment trident` should show a deployment named trident with a single live replica. Running `kubectl get pod` should show a pod with a name starting with trident- with 2/2 containers running. "

The doc says "it is highly recommended to run Trident in its own namespace", in which case it'd be better if the instructions used the recommended approach. With `-n trident` at least some sort of info is returned, so it appears the above paragraph assumes the default namespace. I don't know if I'm making mistakes elsewhere but at least the above seems inconsistent with the recommendation.

**Comment by kangarlou** [comment]
If the `-n` option isn't used with tridentctl, tridentctl assumes you have deployed the trident deployment in the current namespace (it doesn't have to be default namespace). If you're in namespace trident, you don't need to use `-n` option. See the description under step 6 in https://github.com/NetApp/trident#getting-started .

We intentionally made the installer work this way to keep the behavior consistent with the way kubectl works and because not everyone may have access to an arbitrary namesapce.
