### ISSUE TITLE
Clarify kubectl/oc usage in documentation

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#62]
In some template files we have `v1beta1` which should be `v1`.
e.g.: https://github.com/NetApp/trident/blob/b52006d387ac30085173a0586925d33b8e91419b/trident-installer/sample-input/storage-class-ontap-gold.yaml#L1

With that I get:

```
[root@master trident-installer]# kubectl create -f sample-input/storage-class-basic.yaml
Error from server (BadRequest): error when creating "sample-input/storage-class-basic.yaml": the API version in the data (storage.k8s.io/v1beta1) does not match the expected API version (storage.k8s.io/v1)
```

Once I fix `storage-class-basic.yaml`, it works fine:

```
[root@master trident-installer]# kubectl create -f sample-input/storage-class-basic.yaml
storageclass "basic" created
[root@master trident-installer]# kubectl --version
Kubernetes v1.5.2
```
In case different versions should be used for different K8S, then the doc could be updated to remind about that.

**Comment by scaleoutsean** [comment]
Later I looked at the Trident install script and noticed that for OpenShift it's supposed to use `v1`. I have OpenShift, but that doesn't get detected (maybe because I have `kubectl`). This may be why `v1beta1` gets used.

```
oc version
oc v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://1.1.1.1:8443
```

**Comment by kangarlou** [comment]
`storage.k8s.io/v1` was introduced in k8s 1.6. That's why there is another sample input file in the installer bundle called `storage-class-basic-v1.yaml.templ` for 1.6 and later releases. The API resource naming scheme might be different in OpenShift.

If the `oc` binary can be found via $PATH, Trident installer assumes you're running OpenShift and wouldn't care if you have `kubectl` installed on your system or not. Having said that, `tridentctl` currently requires `kubectl`. In the future we should change tridentctl to use `oc` on systems where `kubectl` isn't installed.

**Comment by kangarlou** [comment]
Closing the issue as per c7e7123f8e5a66c7687cec1bc1e19331b6485513 tridentctl can work with both kubectl and oc.
