### ISSUE TITLE
Metadata propagation from persistentVolumeClaim to appliance

### ISSUE THREAD

**Issue by ledroide** [NetApp/trident#658]
Goal : Volume management backwards (from appliance to app/namespace/pvc).
Trigger Kubernetes metadata up to the appliance in order to filter or display matching volumes for a pattern.

Abstract :
* Kubernetes practices heavily uses metadata : resource name, namespace, labels, annotations.
* It's common to set labels to persistentVolumeClaims.
* When a persistentVolumeClaim is created with a storageClass that relies on a netapp-trident backend, netapp-trident triggers an actual volume on the appliance, and creates a persistentVolume resource in the Kubernetes cluster. At this step, the original metadata is lost.

Solution :
* Propagate metedata from persistentVolumeClaim to persistentVolume, then - through the backend - to the actual volume on the appliance.
* Make this metadata manageable from the appliance : query metadata, list, filter, or at least display the metadata.

Actual example showing metadata setting/missing between PVC and PV : 
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cheese-data
  namespace: swisscheese
  labels:
    product: cheese
    origin: swiss
    component: hole
  annotations:
    git-source: github.com/cheese/swiss/hole.git
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
  storageClassName: basic
```
```bash
$ kubectl apply -f swisscheese-pvc.yaml
persistentvolumeclaim/cheese-data created
$ kubectl get pvc/cheese-data
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cheese-data   Bound    pvc-dddb6d63-adc1-4baa-a9ca-212559849507   30Mi       RWO            basic          98s
$ kubectl describe pv/pvc-dddb6d63-adc1-4baa-a9ca-212559849507
```
```
Name:            pvc-dddb6d63-adc1-4baa-a9ca-212559849507
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: csi.trident.netapp.io
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    basic
Status:          Bound
Claim:           swisscheese/cheese-data
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        30Mi
Message:         
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            csi.trident.netapp.io
    FSType:            
    VolumeHandle:      pvc-dddb6d63-adc1-4baa-a9ca-212559849507
    ReadOnly:          false
    VolumeAttributes:      backendUUID=19436b69-8e1e-4292-ba46-c2cf3d3ea1ce
                           internalName=k8spoc_pvc_dddb6d63_adc1_4baa_a9ca_212559849507
                           name=pvc-dddb6d63-adc1-4baa-a9ca-212559849507
                           protocol=file
                           storage.kubernetes.io/csiProvisionerIdentity=1634622753755-8081-csi.trident.netapp.io
```

Additional info - current configuration :
```
$ tridentctl version
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 21.07.2        | 21.07.2        |
+----------------+----------------+

$ kubectl version --short
Client Version: v1.22.2
Server Version: v1.22.2

$ tridentctl get backend ontap-nas -o yaml
[...]
  config:
    aggregate: ""
    autoExportCIDRs:
    - 0.0.0.0/0
    - ::/0
    autoExportPolicy: false
    backendName: ontap-nas
    chapInitiatorSecret: <REDACTED>
    chapTargetInitiatorSecret: <REDACTED>
    chapTargetUsername: <REDACTED>
    chapUsername: <REDACTED>
    clientCertificate: ""
    clientPrivateKey: <REDACTED>
    credentials:
      name: <REDACTED>
      type: <REDACTED>
    dataLIF: 192.168.1.37
    debug: false
    debugTraceFlags: null
    defaults:
      adaptiveQosPolicy: ""
      encryption: "false"
      exportPolicy: default_kube
      fileSystemType: ext4
      mirroring: "false"
      qosPolicy: ""
      securityStyle: unix
      size: 1G
      snapshotDir: "false"
      snapshotPolicy: none
      snapshotReserve: ""
      spaceAllocation: "true"
      spaceReserve: none
      splitOnClone: "false"
      tieringPolicy: ""
      unixPermissions: '---rwxrwxrwx'
    disableDelete: false
    emptyFlexvolDeferredDeletePeriod: ""
    igroupName: ""
    labels: null
    limitAggregateUsage: ""
    limitVolumeSize: 150Gi
    lunsPerFlexvol: ""
    managementLIF: 192.168.1.39
    nfsMountOptions: nfsvers=3,soft,noatime
    password: <REDACTED>
    qtreePruneFlexvolsPeriod: ""
    qtreeQuotaResizePeriod: ""
    qtreesPerFlexvol: ""
    region: ""
    replicationPolicy: ""
    replicationSchedule: ""
    serialNumbers: null
    storage: null
    storageDriverName: ontap-nas
    storagePrefix: k8sdev
    supportedTopologies: null
    svm: SQKUBERNETES
    trustedCACertificate: ""
    usageHeartbeat: ""
    useCHAP: false
    useREST: false
    username: <REDACTED>
    version: 1
    zone: ""
  configRef: ""
  name: ontap-nas
  online: true
  protocol: file
  state: online
```

**Comment by wonderland** [comment]
I guess this would be challenging for a number of reasons, including:

- The backend Ontap system doesn't have a proper way of adding arbitrary metadata to a volume
- Duplicating metadata across multiple levels tends to cause issues over time with inconsistencies. Keeping data in one place and referring to it when needed is the better approach from my experience. 

You can always reference from backend volume to PVC, as the UUID is part of the volume name on the backend. But with that you would then of course need to call the K8s side to retrieve the actual labels for that particular volume. Not sure if that would work for your particular use case.

**Comment by alfonsoalongi** [comment]
Hello,
my company also has a similar issue in the ocp cluster with trident. Currently we have about 200 volumes created with csi driver (ontap-nas) that hosts public administration applications.

On OCP 3.11 with the old netapp.io/trident driver, volumes on ONTAP were created with a friendly (descriptive) name, using the convention "storagePrefix" + "namespace" + "deployment" + "short UID (length 5)". For example the volume name "trident_test_mysql_f0fcd" indicates that the volume is in the test namespace and belongs to the deployment with the name mysql. This was very convenient for us because we knew directly from ontap which namespace and which deployment a volume belonged to. Instead, with the new driver "csi.trident.netapp.io" the names of the volumes created follow the convention "storagePrefix" + UID (length 36), for example trident_pvc_e12460a6_bd34_4c43_8e67_f0ba4d5a6324. Is it possible with the new driver obtain a friendly name for the volumes? On the official documentation I have not found anything about it.

In particular, this cluster now hosts about 200 volumes and it becomes impossible to directly have an overview and understand what they refer to from the NetApp ONTAP GUI. I give an example of when a volume is almost full of what we are forced to do but in reality the convention was also useful for us to monitor the disk occupation of applications.
1) we take the ID of ONTAP and convert it to the PV syntax of OCP
2) We search from OCP that PV to which PVC it ​​belongs.
3) Go to the connected PVC and click on "expand volume".

Having a descriptive name for volumes is useful not only for simply expanding them when they are full and receiving alert emails from Active IQ Unified Manager. The "storage administrator" can get an overview and control storage usage by applications in the ONTAP GUI and simply get reports.
Actually, when a volume is created via the Trident provisioner, it already knows which pvc / deployment / namespace it is related to, so there should be no problem entering this information on ONTAP for example as "description".
Finally this could be a configuration parameter if the developer does not want to change the current behavior and make it similar to that of the old driver.

I read that another problem is actually ONTAP which does not support metadata for the volumes. So I don't know how feasible what is required is. The reference sentence is:
"The backend Ontap system doesn't have a proper way of adding arbitrary metadata to a volume".

**Comment by gnarl** [comment]
Hi @ledroide and @alfonsoalongi,

As @wonderland mentioned it is problematic to set metadata on a volume from the PVC. Feedback that we've received indicates that Storage Administrators typically want to control this information at a higher level.  

In Trident, volume label information can be set during volume provisioning by using the [labels configuration option](https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html) for the backend configuration. Use of volume labels can be further enhanced by taking advantage of the virtual storage pools capability that is available in Trident.

As @wonderland mentioned this meta data information can be retrieved from Kubernetes. Closing this issue as the functionality currently exists.

**Comment by ledroide** [comment]
@gnarl : Maybe I'm wrong somehow, but I have actually tried this option "labels" at the backend level. This feature sets a permanent label to all volumes that are provided by the backend.
The, all volumes on the appliance's SVM get the same label. It is useless for our use case.

Labels propagation from the PersistentVolumeClaim to the volume sets potentially different labels and values for every PVC, PV, and matching volume on the NetApp.
Reversely, from a volume, we can see the original PVC's label. Let's say : `app: loki` ; `data: logs` , etc. 
With such labels, we an monitor the SVM volumes (space left, inodes, etc) AND know where the problem can be solved on the cluster.

Obviously this is not the purpose of the [labels configuration option](https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html)
