### ISSUE TITLE
setting nfsMountOptions: 'vers=4' results in error (exit status 32)

### ISSUE THREAD

**Issue by domruf** [NetApp/trident#741]
**Describe the bug**
When I set `nfsMountOptions: 'vers=4'` I get this errors like this
```
MountVolume.SetUp failed for volume "pvc-5fac2bac-b21f-4d7d-ab7a-d5a56381ac77" : rpc error: code = Internal desc = error mounting NFS volume <myip>:/my:storagePrefix_pvc_5fac2bac_b21f_4d7d_ab7a_d5a56381ac77 on mountpoint /var/lib/kubelet/pods/0cef26a5-8966-472e-b7c1-7cd4d568ff66/volumes/kubernetes.io~csi/pvc-5fac2bac-b21f-4d7d-ab7a-d5a56381ac77/mount: exit status 32
```
With no nfsMountOptions or with `nfsMountOptions: 'ro'` it works fine.
I see no more information about why the mount failed.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: trident:21.07.2
- Trident installation flags used: unknown
- Container runtime: docker 20.10.10
- Kubernetes version: v1.21.7
- Kubernetes orchestrator: Rancher v2.6.3
- Kubernetes enabled feature gates: unknown
- OS: Ubuntu 18.04.6 LTS
- NetApp backend types: ONTAP
- Other:

**To Reproduce**
- set `nfsMountOptions: 'vers=4'` in TridentBackendConfig or StorageClass
- create pod which is using the TridentBackendConfig or StorageClass

**Expected behavior**
The nfs export gets mounted without error.

**Comment by gnarl** [comment]
Hi @domruf,

This error is being returned as an error when executing the mount binary. The [manual page for mount(8)](https://linux.die.net/man/8/mount) lists the return code of 32 as "mount failure". The mount failure can occur for numerous configuration issues either on the Kubernetes worker node or in the configuration of the storage backend. 

One recommended approach is to access your Kubernetes worker node and run the mount command. Use this method to troubleshoot why the mount operation is failing. I'm closing this GitHub issue since this isn't a Trident specific issue. Trident will execute the provided mount options when attempting to mount an NFS volume. Please contact NetApp support if you need additional assistance.
