### ISSUE TITLE
Update meta data in Red Hat OpenShift project

### ISSUE THREAD

**Issue by sabman3** [NetApp/trident#907]
NetApp docs show Trident is supported on OpenShift 4.15, however the operator is not available in the Operator Hub. This is because the meta data only show that OpenShift 4.10 to 4.14 is supported. Please update the meta data to show OpenShift 4.15 is supported if possible.

https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/trident-operator/24.2.0/metadata/annotations.yaml

Current:
com.redhat.openshift.versions: v4.10-v4.14

New/Requested:
com.redhat.openshift.versions: v4.10-v4.15

**Comment by eselvam** [comment]
you can download and install offline bundle and it is very straight forward install.  The Trident document has clear instruction.  Kindly go through it.

**Comment by benruland** [comment]
I had created a PR for that (https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4721 and https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/4658), but it needs to be configured for a new release. 

The version v24.06.0 could be added with the new supported versions.

OpenShift 4.16 is also out with Kubernetes 1.29 under the hood. As K8S 1.29 is also supported in Trident, is there also support for OpenShift 4.16?

**Comment by reederc42** [comment]
@benruland I responded to your issue on community-operators-prod (https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/4658#issuecomment-2231469340)

For Trident 24.06.0 I've removed the version annotations so that there are no technical restrictions to installing Trident on any version of openshift, but our support policies remain that we only fully support the listed versions of k8s/openshift.

**Comment by benruland** [comment]
Thanks! I would consider this issue closed then!

PR is https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4771
