### ISSUE TITLE
Do I require having multipathd enabled to use iSCSI?

### ISSUE THREAD

**Issue by rabin-io** [NetApp/trident#920]
**Describe the bug**
$subect

**Environment**
I'm testing Trident on top of OpenShift, and started to test iSCSI (on-san) support as a backend for Virtual Machines (OpenShift Virtualization).

- Trident version: 24.06.1
- Trident installation flags used: 
- NetApp backend types: NetApp Release 9.10.1P5 
- Other:

**To Reproduce**
Create a VM and an add a disk using the iSCSI storage class.

**Expected behavior**
Should just work. But I get an error message

```
Warning FailedMapVolume 69s (x9 over 3m18s) kubelet MapVolume.SetUpDevice failed for volume "pvc-357308a4-b673-4e90-9557-85b71f1eb525" : rpc error: code = Internal desc = rpc error: code = Internal desc = failed to stage volume: multipathd is not running
```

**Additional context**
Enabling multipathd on the host, does resolve this issue, but I'm wondering if enabling `multipathd` is required for iSCSI, or it is just a config on the TridentBackEnd config?

![image](https://github.com/user-attachments/assets/e1078aa4-f6ad-41f6-ab8c-c215e3b3862e)

**Comment by wonderland** [comment]
Yes, multipathing is required. You'll run into issues otherwise if any failover/maintenance occurs on the storage system. Therefore recent versions of Trident enforce multipathing. 

You can set this via MachineConfig. The only setting Trident needs in multipath.conf is `find_multipaths no`. An example MachineConfig is provided here (please refer to the one for multipathing!): https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html#iscsi

**Comment by rabin-io** [comment]
Thank you for the (quick) clarification.
